export const ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  PASSWORD_MISMATCH: "PASSWORD_MISMATCH",

  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
  AUTH_FORBIDDEN: "AUTH_FORBIDDEN",
  AUTH_REFRESH_MISSING: "AUTH_REFRESH_MISSING",
  AUTH_REFRESH_INVALID: "AUTH_REFRESH_INVALID",

  DB_UNIQUE_CONSTRAINT: "DB_UNIQUE_CONSTRAINT",
  DB_NOT_FOUND: "DB_NOT_FOUND",
  DB_CONSTRAINT: "DB_CONSTRAINT",

  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",

  AUCTION_CATEGORY_NOT_FOUND: "AUCTION_CATEGORY_NOT_FOUND",
  AUCTION_CATEGORY_SLUG_ALREADY_EXISTS: "AUCTION_CATEGORY_SLUG_ALREADY_EXISTS",
  AUCTION_CATEGORY_IN_USE: "AUCTION_CATEGORY_IN_USE",
} as const;
export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
