export const ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  PASSWORD_MISMATCH: "PASSWORD_MISMATCH",

  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
  AUTH_FORBIDDEN: "AUTH_FORBIDDEN",
  AUTH_REFRESH_MISSING: "AUTH_REFRESH_MISSING",
  AUTH_REFRESH_INVALID: "AUTH_REFRESH_INVALID",

  USER_EMAIL_ALREADY_EXISTS: "USER_EMAIL_ALREADY_EXISTS",

  DB_UNIQUE_CONSTRAINT: "DB_UNIQUE_CONSTRAINT",
  DB_NOT_FOUND: "DB_NOT_FOUND",
  DB_CONSTRAINT: "DB_CONSTRAINT",

  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",

  AUCTION_CATEGORY_NOT_FOUND: "AUCTION_CATEGORY_NOT_FOUND",
  AUCTION_CATEGORY_SLUG_ALREADY_EXISTS: "AUCTION_CATEGORY_SLUG_ALREADY_EXISTS",
  AUCTION_CATEGORY_IN_USE: "AUCTION_CATEGORY_IN_USE",

  AUCTION_NOT_FOUND: "AUCTION_NOT_FOUND",
  AUCTION_CODE_ALREADY_EXISTS: "AUCTION_CODE_ALREADY_EXISTS",
  AUCTION_SLUG_ALREADY_EXISTS: "AUCTION_SLUG_ALREADY_EXISTS",
  AUCTION_INVALID_SLUG: "AUCTION_INVALID_SLUG",
  AUCTION_INVALID_TIME_RANGE: "AUCTION_INVALID_TIME_RANGE",
  AUCTION_INVALID_PRICE: "AUCTION_INVALID_PRICE",
  AUCTION_UPDATE_NOT_ALLOWED: "AUCTION_UPDATE_NOT_ALLOWED",
  AUCTION_DELETE_NOT_ALLOWED: "AUCTION_DELETE_NOT_ALLOWED",
  AUCTION_ALREADY_ENDED: "AUCTION_ALREADY_ENDED",
  AUCTION_INVALID_STATUS: "AUCTION_INVALID_STATUS",

  AUCTION_IMAGE_NOT_FOUND: "AUCTION_IMAGE_NOT_FOUND",

  BID_NOT_FOUND: "BID_NOT_FOUND",
  BID_AUCTION_NOT_LIVE: "BID_AUCTION_NOT_LIVE",
  BID_AUCTION_NOT_STARTED: "BID_AUCTION_NOT_STARTED",
  BID_AUCTION_ALREADY_ENDED: "BID_AUCTION_ALREADY_ENDED",
  BID_SELF_BIDDING_NOT_ALLOWED: "BID_SELF_BIDDING_NOT_ALLOWED",
  BID_AMOUNT_TOO_LOW: "BID_AMOUNT_TOO_LOW",
  BID_CONSECUTIVE_SELF_BID_NOT_ALLOWED: "BID_CONSECUTIVE_SELF_BID_NOT_ALLOWED",
  BID_TOO_FREQUENT: "BID_TOO_FREQUENT",
  BID_RATE_LIMIT_EXCEEDED: "BID_RATE_LIMIT_EXCEEDED",
  BID_INVALID_AMOUNT: "BID_INVALID_AMOUNT",
  BID_AUCTION_NOT_FOUND: "BID_AUCTION_NOT_FOUND",
  BID_WALLET_NOT_FOUND: "BID_WALLET_NOT_FOUND",
  BID_INSUFFICIENT_AVAILABLE_BALANCE: "BID_INSUFFICIENT_AVAILABLE_BALANCE",
  BID_CONCURRENT_CONFLICT: "BID_CONCURRENT_CONFLICT",
  BID_AUCTION_PRICE_CHANGED: "BID_AUCTION_PRICE_CHANGED",

  AUCTION_FEATURE_NOT_FOUND: "AUCTION_FEATURE_NOT_FOUND",
  AUCTION_FAQ_NOT_FOUND: "AUCTION_FAQ_NOT_FOUND",

  WALLET_NOT_FOUND: "WALLET_NOT_FOUND",
  WALLET_INVALID_STATE: "WALLET_INVALID_STATE",
  WALLET_INSUFFICIENT_AVAILABLE_BALANCE:
    "WALLET_INSUFFICIENT_AVAILABLE_BALANCE",
  WALLET_HOLD_CONFLICT: "WALLET_HOLD_CONFLICT",
  WALLET_LOCKED_BALANCE_INCONSISTENT: "WALLET_LOCKED_BALANCE_INCONSISTENT",
  DEPOSIT_ORDER_INVALID_AMOUNT: "DEPOSIT_ORDER_INVALID_AMOUNT",
  DEPOSIT_ORDER_NOT_FOUND: "DEPOSIT_ORDER_NOT_FOUND",
  DEPOSIT_ORDER_ALREADY_PAID: "DEPOSIT_ORDER_ALREADY_PAID",
  DEPOSIT_ORDER_INVALID_STATUS: "DEPOSIT_ORDER_INVALID_STATUS",
  WITHDRAWAL_REQUEST_NOT_FOUND: "WITHDRAWAL_REQUEST_NOT_FOUND",
  WITHDRAWAL_REQUEST_INVALID_STATUS: "WITHDRAWAL_REQUEST_INVALID_STATUS",
  WALLET_HOLD_NOT_FOUND: "WALLET_HOLD_NOT_FOUND",
  PAYMENT_PROVIDER_UNSUPPORTED: "PAYMENT_PROVIDER_UNSUPPORTED",
  PAYMENT_WEBHOOK_INVALID: "PAYMENT_WEBHOOK_INVALID",

  AUCTION_SETTLEMENT_NOT_FOUND: "AUCTION_SETTLEMENT_NOT_FOUND",
  AUCTION_SETTLEMENT_FAILED: "AUCTION_SETTLEMENT_FAILED",
} as const;
export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
