export const ERROR_CODES = {
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  PASSWORD_MISMATCH: "PASSWORD_MISMATCH",

  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
  AUTH_FORBIDDEN: "AUTH_FORBIDDEN",
  AUTH_REFRESH_MISSING: "AUTH_REFRESH_MISSING",
  AUTH_REFRESH_INVALID: "AUTH_REFRESH_INVALID",

  DB_UNIQUE_CONSTRAINT: "DB_UNIQUE_CONSTRAINT",
  DB_NOT_FOUND: "DB_NOT_FOUND",
  DB_CONSTRAINT: "DB_CONSTRAINT",

  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",

  AUCTION_CATEGORY_NOT_FOUND: "AUCTION_CATEGORY_NOT_FOUND",
  AUCTION_CATEGORY_SLUG_ALREADY_EXISTS: "AUCTION_CATEGORY_SLUG_ALREADY_EXISTS",
  AUCTION_CATEGORY_IN_USE: "AUCTION_CATEGORY_IN_USE",

  AUCTION_NOT_FOUND: "AUCTION_NOT_FOUND",
  AUCTION_CODE_ALREADY_EXISTS: "AUCTION_CODE_ALREADY_EXISTS",
  AUCTION_SLUG_ALREADY_EXISTS: "AUCTION_SLUG_ALREADY_EXISTS",
  AUCTION_INVALID_SLUG: "AUCTION_INVALID_SLUG",
  AUCTION_INVALID_TIME_RANGE: "AUCTION_INVALID_TIME_RANGE",
  AUCTION_INVALID_PRICE: "AUCTION_INVALID_PRICE",
  AUCTION_UPDATE_NOT_ALLOWED: "AUCTION_UPDATE_NOT_ALLOWED",
  AUCTION_DELETE_NOT_ALLOWED: "AUCTION_DELETE_NOT_ALLOWED",
  AUCTION_ALREADY_ENDED: "AUCTION_ALREADY_ENDED",

  AUCTION_IMAGE_NOT_FOUND: "AUCTION_IMAGE_NOT_FOUND",

  BID_NOT_FOUND: "BID_NOT_FOUND",
  BID_AUCTION_NOT_LIVE: "BID_AUCTION_NOT_LIVE",
  BID_AUCTION_NOT_STARTED: "BID_AUCTION_NOT_STARTED",
  BID_AUCTION_ALREADY_ENDED: "BID_AUCTION_ALREADY_ENDED",
  BID_SELF_BIDDING_NOT_ALLOWED: "BID_SELF_BIDDING_NOT_ALLOWED",
  BID_AMOUNT_TOO_LOW: "BID_AMOUNT_TOO_LOW",

  AUCTION_FEATURE_NOT_FOUND: "AUCTION_FEATURE_NOT_FOUND",
  AUCTION_FAQ_NOT_FOUND: "AUCTION_FAQ_NOT_FOUND",
} as const;
export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
